- .github/workflows/KubernetesInternalClients.yaml
- KubernetesInternalClients/go/Dockerfile
- KubernetesInternalClients/go/go.mod
We were checking out the given branch and using repalce in go.mod file, the apporach is changed with this PR
> Relative import strategy is changed for go client

- .github/workflows/KubernetesExternalClients.yaml
- KubernetesExternalClients/nodejs/client.js
Parameter pass from one job to other jobs were a bit dirty, now it is handled with outputs feature of github action
> Passing parameters from one job to other job strategy is changes

- .github/workflows/csharp_client_compatibility.yaml
Filter for Remote namcespace is removed, all tests will be run as backward compatibility
> Remove Remote namespace filter

- .github/workflows/csharp_client_compatibility.yaml
- .github/workflows/server_compatibility.yaml
Workflows was missing the .Net6. Also, hz script in Client `v4.1.0` doesn't set server version, that causes to fail tests. Fixed on workflow.
> Net6 and HZ Version 

- .github/workflows/csharp_client_compatibility.yaml
- .github/workflows/server_compatibility.yaml
Reordered the hz server version set to before tests run.
> Reordered the steps

- .github/workflows/server_compatibility.yaml
We tried to add this step to make the C# scripts work, but it wasn't
enough.
> Remove config extractor step

- .github/workflows/KubernetesExternalClients.yaml
- KubernetesExternalClients/nodejs/client.js
Did not update other clients because don't know how to update their code. 
Simplified node.js client script and workflow. It is enough to exit with zero code
> Update kubernetes external client node.js result checking and refactor the node.js script

- .github/workflows/KubernetesExternalClients.yaml
- .github/workflows/KubernetesInternalClients.yaml
- KubernetesInternalClients/csharp/Dockerfile
Workflow keeps failing due to timeout for cluster deployment, so increased. Also, fixed folder path on Docker file for .Net client.
> Increase timeout and Fix Docker Path for .Net Client

- .github/workflows/KubernetesExternalClients.yaml
- KubernetesExternalClients/csharp/KubernetesTest/Program.cs
The way of creating k8s cluster is changed. Cluster is created with Hazelcast Operator. It allows Hazelcast members to have public IP. Also, auth to GKE is updated with latest action.
Test Passed ✅ 
(updated) https://github.com/emreyigit/client-compatibility-suites/actions/runs/4063191849
> Fix k8s external

- .github/workflows/cloud_csharp_client_test.yaml
- .github/workflows/cloud_go_client_test.yaml
- .github/workflows/cloud_java_client_test.yaml
- .github/workflows/cloud_nodejs_client_test.yaml
- .github/workflows/cloud_python_client_test.yaml
- .github/workflows/nodejs_client_compatibility.yaml
- .github/workflows/python_client_compatibility.yaml
- .github/workflows/server_compatibility.yaml
5.4 hazelcast does not support java 8 anymore 
followup to https://github.com/hazelcast/client-compatibility-suites/pull/81 after fail https://github.com/hazelcast/client-compatibility-suites/actions/runs/7260171572
> Update java to 11 in all places

- .github/java-config.yml
- .github/workflows/server_compatibility.yaml
We checkout to master directory that's why we need this change
> Fix path yaml reader path in server compat workflow

- .github/workflows/server_compatibility.yaml
- utils/net/no-java-check/hz.ps1
This PR overrides `hz.ps1` of released .Net clients with no Java version check one.
> Use hz.ps1 with no Java check.

- .github/workflows/server_compatibility.yaml
In #107 I used wrong path, master removed from the path .
See fail in https://github.com/hazelcast/client-compatibility-suites/actions/runs/9837297462
> Fix path in read yaml step

- .github/workflows/server_compatibility.yaml
This PR applies https://hazelcast.slack.com/archives/C07BCQKKHHB/p1721647036269379?thread_ts=1721394454.184319&cid=C07BCQKKHHB
> By default don't run unsupported clients

- .github/workflows/server_compatibility.yaml
- utils/net/ssl/src/Hazelcast.Net.Testing/TestFiles.cs
Fixes version check for SSL compatibility and filters out CP tests for OS server.
> Fix .Net Client Tests

- .github/workflows/java_client_compatibility.yaml
Fixed the config file path for the Java client workflow.
> Fix config file path for the Java client workflow

- .github/workflows/server_compatibility.yaml
to fix https://github.com/hazelcast/client-compatibility-suites/actions/runs/11235297003/job/31233960836
> Update versions to v4 API-2265

- .github/workflows/java_client_compatibility.yaml
- .github/workflows/server_compatibility.yaml
This PR includes: 
1. the vector module was added to run related tests with enterprise server
2. I added skipping redundant run of OS tests against enterprise sever since we run them agains OS server and they should work agains enterprise server by default
> PA-597 Java standalone client changes

- start_remote_controller.py
- util.py
Port of the resolution to the issue described in https://github.com/hazelcast/hazelcast-cpp-client/pull/1206
[Slack discussion](https://hazelcast.slack.com/archives/C082AEKKLEA/p1738231728482419)
[Example run to demonstrate issue addressed (in progress)](https://github.com/hazelcast/client-compatibility-suites/actions/runs/13052053621).
> Update dependency:get command to latest syntax

- .github/workflows/java_client_compatibility.yaml
Incorrect initialization caused the workflow to fail.
> PA-613 Fix matrix.tests_type parameter initialization
