hazelcast/client-compatibility-suites

KubernetesExternalClients/python/client.py, KubernetesInternalClients/python/client.py, get_server_matrix.py, util.py
With this change, we will also include v5 servers in the client
compatibility tests.
The change simply adds a v5 server release filter and introduces
an extra logic to parse another file to get sources, since the
5.x server releases will be put into a different file.
=> Return v5 servers while constructing the matrix

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/KubernetesInternalClients.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml, KubernetesInternalClients/nodejs/Dockerfile
For all compatibility tests(K8s and backward), node version was `14` it is set to `10.4` now
Organization name is set as parametric.
When a developer would like to run compatibility test with his forked repo, he can set the `organiation_name` parameter to his github name.
=> Nodejs version is set to 10.4, parametric organization name is added

.github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
After dropping support for Python2, the nosetest dependency is replaced
with pytest.
This PR updates the test runners with the new dependency.
=> Use pytest as the test runner for Python client tests

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/server_compatibility.yaml, KubernetesInternalClients/nodejs/Dockerfile
This is a required change, as in Node.js 10.4, the tests were failing
due to client not being able to close connections.
The client was relying on the fact that writes to an already closed
socket would throw an error and the client would be able to close the
that connection, but that is not happening on Node.js 10.4.
Looking at the recent changes done by Serkan on the Node.js client,
it seems it is possible to work around that problem but that requires
a change in the client code, and we cannot do that for already
released clients.
So, we have to revert the Node.js version back and look for long-term
solutions once Serkan is back.
=> Revert Node.js version to 14

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/KubernetesInternalClients.yaml, .github/workflows/nodejs_client_compatibility.yaml
Nodejs client repo counterpart: https://github.com/hazelcast/hazelcast-nodejs-client/pull/1092
Also, soak tests will be run via:
1. Downloading release pack using the same nodejs script used here.
2. Extracting lib and using that lib folder. 
**NOTE: This pr may not be necessary, if we decide not to run any test after packing. In that case I will close this pr.**
=> Nodejs new release flow api-929

util.py
Fixes https://github.com/hazelcast/client-compatibility-suites/runs/6130345800?check_suite_focus=true by disabling transitive dependencies.
=> Disable transitive dependencies

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/go_client_compatibility.yaml, HazelcastCloudTests/gohazelcastcloudtests/go.mod, KubernetesExternalClients/go/go.mod, KubernetesInternalClients/go/Dockerfile, KubernetesInternalClients/go/go.mod
Latest version of the Go client requires 1.17. Upgraded the Go version to 1.18 to be a bot more future-proof.
=> [TRIVIAL] Upgraded Go to 1.18

.github/workflows/server_compatibility.yaml
Not to download from maven or a repo, required files should be in the directory. Config file was missing. A step added to extract the default xml file to lib directory as `hazelcast-{version}.xml`.
=> Missing Config file extracted from JAR file

.github/workflows/cloud_go_client_test.yaml
The default installed version of Go in the workflow container for the Cloud test is 1.17. This PR installs Go explicitly.
=> Explicitly install go

.github/workflows/server_compatibility.yaml, tests-jar.diff
We don't generate the tests JAR anymore in 5.2.0. But, we haven't updated the client compatibility tests to drop the dependency on it.
This PR adds the git diff to patch the enterprise code so that it also generates the tests JAR.
We should revert these changes once we implement the proper solution.
=> Generate tests-jar for 5.2.0

.github/workflows/server_compatibility.yaml
Due to client not being able to compile on Ubuntu-22.04, we have to run C++ tests on Ubuntu-20.04, until we sort the problems with the recent OpenSSL versions in the clients, and make them compile again.
=> Run C++ tests with Ubuntu-20.04

.github/workflows/csharp_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml
In workflows where we use
```
- name: Checkout to scripts
uses: actions/checkout@v2
```
we should checkout to other repos after that, so that they can be placed under the $GITHUB_WORKSPACE correctly.
=> Checkout to private-test-artifacts repo after checking out to master

.github/workflows/server_compatibility.yaml
Somehow, the parameter expansion in the command was not working, and failing with an error message `bad substitution`.
I now use sed to replace the string. Also, I have simplified finding the correct test-jar name according to Serkan's suggestion.
=> Use sed to replace strings

KubernetesInternalClients/cpp/Dockerfile
Github actions fails because resource limits are exceeded I guess.
=> Parallel jobs are disabled due to resource excess.

.github/workflows/csharp_client_compatibility.yaml
The script is capable of generating certificates or downloading them. With these changes, it should be able to detect the certificates are missing and either generate them or download them using the provided token.
=> Let the C# script handle certificates

.github/workflows/csharp_client_compatibility.yaml
Upgraded Java 8 to 11 since keystore format (PKCS12) that we use in tests is not compatible  with Java 8. So, that upgraded the Java version.
=> Upgrade Java Version on Workflow

KubernetesInternalClients/csharp/KubernetesTest/Program.cs
It seems retry timeout must be bigger than kubectl timeout which is changed here https://github.com/hazelcast/client-compatibility-suites/pull/61
=> Increase retry timeout for .net client.

.github/workflows/cpp_client_compatibility.yaml
Since this repo is public there is no fee to run compatibility tests nightly. These tests are generally blocker for us when we are close to release dates. So enabling nightly build will allow us to see before we are about to release.
=> Enable nightly build for cpp-client

.github/workflows/server_compatibility.yaml
We've fixed the SSL tests for <5.2. The fix was also include run with Hazelcast BETA snapshots. Although, client 5.2 doesn't have any issues with ssl tests, it fails due to BETA versioning. By increasing the backward fix coverage, the hz.ps1 script will run tests with BETA snapshots.
=> Increase compt. version for tests.

.github/workflows/cloud_csharp_client_test.yaml
Because the .NET tests regularly fail and it's hard to figure out whether it's due to Viridian acting weird or an issue with our tests or an actual bug, this PR ensures that we upload the tests results as artifacts. They can then be explored and contain valuable info for us.
=> Fix .NET cloud tests, upload the tests logs as artifacts

.github/workflows/cpp_client_compatibility.yaml
It fails constantly, and there is no active development in the C++ client. Therefore, I think it makes sense to remove the nightly tests.
=> Remove nightly run for C++ client

.github/workflows/server_compatibility.yaml
It helps the improve condition on ssl tests coping for older versions.
=> More specific condition on version.

.github/workflows/server_compatibility.yaml
Needed for 5.4 release. See https://github.com/hazelcast/client-compatibility-suites/actions/runs/7253539308/job/19760341566
=> Update java to 11 in server compat tests

.github/java-config.yml, .github/workflows/cloud_csharp_client_test.yaml, .github/workflows/cloud_go_client_test.yaml, .github/workflows/cloud_java_client_test.yaml, .github/workflows/cloud_nodejs_client_test.yaml, .github/workflows/cloud_python_client_test.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
As part of Hazelcast 5.4 moving to Java 17, the GitHub actions need to be configured to use the newer Java version.
Changes:
- configuration externalised to make future updates easier
- Java version now consistently 17 (was a mix of 8 & 11)
- Java distribution now consistently Temurin (was a mix of AdoptOpenJDK & Zulu)
- GitHub actions upgraded to latest
- `actions/checkout`
- `actions/setup-java`
Fixes [HZ-4166](https://hazelcast.atlassian.net/browse/HZ-4166)
[HZ-4166]: https://hazelcast.atlassian.net/browse/HZ-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update GitHub actions to Java 17 [HZ-4166]

.github/workflows/server_compatibility.yaml
The old workflow was according to os + ee, now we should use monorepo. 
test run on my fork https://github.com/srknzl/client-compatibility-suites/actions/runs/7817890850
=> Monorepo changes for server compat workflow

utils/net/hz-latest.ps1
Now that [`hazelcast-remote-controller` supports Java 17](https://github.com/hazelcast/hazelcast-remote-controller/pull/69), the guard case preventing this can be removed.
=> Remove Java >=15 guard case

utils/net/ssl/src/Hazelcast.Net.Tests/Networking/ClientSslTestBase.cs
Java doesn't like null certificate names anymore. Although it's fixed in `master` older releases didn't get that update on tests. So, PR includes a fix for older .Net client releases on SSL tests with a default dummy certificate name.
=> Java doesn't like null Cert Name-Fixes Failing SSL Tests on .Net Client

.github/workflows/server_compatibility.yaml
NUnit Adapter version is annoying with .Net 8 runtime. I added a fix that upgrades nunit adapter version on .Net client v5.2.2 and .Net client v5.3.1 in `Hazelcast.Net.Tests.csproj`
=> Upgrade NUnit Adapter on .Net client 5.2.2 and 5.3.1

.github/workflows/cloud_csharp_client_test.yaml, .github/workflows/cloud_go_client_test.yaml, .github/workflows/cloud_java_client_test.yaml, .github/workflows/cloud_nodejs_client_test.yaml, .github/workflows/cloud_python_client_test.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
Currently we are referencing a tag when specifying the version of the `action-read-yaml` action, which is potentially mutable.
[It was requested](https://github.com/hazelcast/hazelcast-mono/pull/1181#discussion_r1537109860) that the commit SHA be used instead, as per the [GitHub actions security hardening guide](https://github.com/hazelcast/hazelcast-mono/pull/1181#discussion_r1537109860).
Updated the version specification to the commit hash of the [currently used version](https://github.com/pietrobolcato/action-read-yaml/releases/tag/1.1.0) - i.e. no changes to the actual version of the action being used.
=> Use commit hash (not tag) for `action-read-yaml` action version specification

get_client_matrix.py, get_server_matrix.py, util.py
These versions are not supported anymore. Thus I remove them from testing.
You can test the change by running 
* python3 get_client_matrix.py --client py --option tag --use-latest-patch-versions
* python3 get_client_matrix.py --client go --option tag --use-latest-patch-versions
* python3 get_server_matrix.py
=> Ignore 4.0.z and 1.0.z & 1.1.z (go) versions in tests

KubernetesInternalClients/csharp/KubernetesTest/Program.cs
Reconnect modes are implemented in .Net client as it should be. So, async mode throws as expected and sync doesn't. So, test is designed for sync reconnect mode.
=> Fix reconnect mode on .Net k8s Test

utils/net/no-java-check/hz.ps1
Now `5.4.0` is released, the released version should be used in preferences to a pre-release `SNAPSHOT`.
=> Use released Hazelcast `5.4.0` instead of `SNAPSHOT`

.github/java-config.yml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
Reverts https://github.com/hazelcast/client-compatibility-suites/commit/a7b74d1dd0cd48f28d4eeaf8da5983c015578fe8 partially for csharp
It does not work because csharp runs on windows. Can be reverted back to env approach after the releases depending on client compat tests are complete.
=> Revert reading from github env for csharp client 

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/KubernetesInternalClients.yaml, .github/workflows/cloud_csharp_client_test.yaml, .github/workflows/cloud_go_client_test.yaml, .github/workflows/cloud_nodejs_client_test.yaml, .github/workflows/cloud_python_client_test.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
[Recent builds](https://github.com/hazelcast/client-compatibility-suites/actions/runs/9872933102) have produced warnings:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-python@v2, actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Upgrade `checkout` and `setup-python` to the latest versions to resolve.
=> Upgrade GitHub actions to avoid deprecated `node` warnings

.github/workflows/server_compatibility.yaml
Using the `quick` profile we can drop the Maven build time from [14 minutes](https://github.com/hazelcast/client-compatibility-suites/actions/runs/9876973263/job/27277425629) to [12 minutes](https://github.com/hazelcast/client-compatibility-suites/actions/runs/9877063468/job/27277738607).
=> Make server compatibility Maven build quicker

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/KubernetesInternalClients.yaml, KubernetesExternalClients/java/.gitignore, KubernetesExternalClients/java/pom.xml, KubernetesExternalClients/java/src/main/java/KubernetesExternalTest.java, KubernetesInternalClients/java/.gitignore, KubernetesInternalClients/java/Dockerfile, KubernetesInternalClients/java/dependency-reduced-pom.xml, KubernetesInternalClients/java/pom.xml, KubernetesInternalClients/java/src/main/java/KubernetesInternalTest.java, KubernetesInternalClients/java/src/main/resources/log4j2.properties, set_which_client_run.py
Adds thin java client tests similar to other tests. Test runs on [thin-client-kubernetes](https://github.com/hazelcast/client-compatibility-suites/tree/thin-client-kubernetes) branch: 
Internal: https://github.com/hazelcast/client-compatibility-suites/actions/runs/10605238016 passed ✅ 
External: https://github.com/hazelcast/client-compatibility-suites/actions/runs/10605726683 passed ✅ 
the code in thin-client-kubernetes branch in this repo is identical to the fork branch (source branch of this PR)
=> Add the java client external & internal kubernetes test

.github/workflows/java_client_compatibility.yaml, .github/workflows/java_thin_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
While building Java Standalone Client via maven, hazelcast-enterprise jar file couldn't be found. 
Fixes: 
1. Changed the way of installing jars to local maven 
2. Fixed a problem with getting license key from secrets for server versions <5.5
3. Changed version of actions/upload-artifact and actions/download-artifact to v4 since v2 is deprecated. 
4. Changed the default branch name to master in java_thin_client_compatibility.yaml
=> Fix for finding the hazelcast-enterprise jar during the builds [Pa 327]

.github/workflows/java_client_compatibility.yaml
Platform does not test compat tests with other jvms. We should not do it as well. It'll consume a lot of resources because ubicloud is not planned for client-compatibility-suites repo. 
There're 96 jobs that some of which takes 4 hours to run, it's not feasible to run that many combinations
see https://github.com/hazelcast/client-compatibility-suites/actions/runs/11034999323
=> Remove matrix from java compat suites

.github/workflows/java_client_compatibility.yaml
Read environment variables from the config file and set the environment variables properly. Specifically the `env.JAVA_VERSION` and `env.JAVA_DISTRIBUTION` variables.
=> Read environment variables from the config file for Java Client compatibility test [PA-343]

.github/workflows/java_client_compatibility.yaml
Use java version from environment for all uses. Replace `matrix.java.version` with `env.JAVA_VERSION`.
=> Use java version from environment for all uses [PA-343]

.github/workflows/java_client_compatibility.yaml
2 input parameters were added to the workflow: 
1. tests_type - regulates what kind of tests we want to run - open-source or enterprise. 
2. test_filter - enables the user to run a separate test, set of tests, etc. The value of this parameter goes to -Dtest maven parameter and should satisfy its syntax.
=> PA-613 Add input parameters for tests type and mvn -Dtest

.github/workflows/cloud_csharp_client_test.yaml, .github/workflows/cloud_go_client_test.yaml, .github/workflows/cloud_nodejs_client_test.yaml, .github/workflows/cloud_python_client_test.yaml
GitHub are now [preventing builds with outdated versions of `upload-artifact` from running](https://github.com/hazelcast/hazelcast-docker/actions/runs/13172853058):
> This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
As such upgraded to the latest version.
=> Upgrade `upload-artifact` from a non-deprecated version

.github/workflows/cpp_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail.
I have not tested this change, if problems are reported we can address them as they occur - but we must upgrade to ensure the builds _actually work_.
=> GH Action test

.github/workflows/python_client_compatibility.yaml
Outdated certificates caused a [test failure](https://github.com/hazelcast/client-compatibility-suites/actions/runs/14998179569/job/42138824244).
There was [an action](https://github.com/hazelcast/hazelcast-python-client/actions/runs/14766960347/workflow) to update these automatically in the repo, but due to new branch protection [it's failing](https://github.com/hazelcast/hazelcast-python-client/actions/runs/14766960347/job/41460207509).
Rather than update the source code, we can simply hot-replace the certificates before we test as per https://github.com/hazelcast/hazelcast-nodejs-client/pull/1535.
[Example execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15025997762).
Post-merge actions:
=> Use dynamic/latest certificates in Python

.github/actions/get-enterprise-license/action.yml, .github/workflows/cloud_csharp_client_test.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/java_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
Different version of Hazelcast platform need different formats of license keys to unlock various features.
The logic around which version requires which license is duplicated and in any case is missing the full range of cases, causing test failures.
This PR:
- centralises setting the enterprise license key logic
- refactors everything to use it
- ensures all three cases of license are handled
- sets the `madhead/semver-utils` version by SHA as per GitHub security guidelines
- they were already conflicting _anyway_ so I had to pick something
Example [compatibility-tests execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15062951610), test output of just the `get-enterprise-license` bit [here](https://github.com/hazelcast/client-compatibility-suites/actions/runs …
=> Centralise setting license

KubernetesInternalClients/cpp/Dockerfile
Replicates fix in https://github.com/hazelcast/hazelcast-cpp-client/pull/1257 to fix [build failure](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15277137314).
=> Fix `boost` installation script

.github/java-config.yml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
Reverts change in https://github.com/hazelcast/client-compatibility-suites/pull/107, and updates original implementation to run in bash (not powershell) as per [the C++ client](https://github.com/hazelcast/hazelcast-cpp-client/blob/9ca294413ade65417d4d368dd6918a49179c3a58/.github/actions/build-test/windows/action.yml#L55) on Windows.
=> Revert "Revert reading from github env for csharp client"

.github/workflows/KubernetesExternalClients.yaml, .github/workflows/KubernetesInternalClients.yaml, .github/workflows/cpp_client_compatibility.yaml, .github/workflows/csharp_client_compatibility.yaml, .github/workflows/go_client_compatibility.yaml, .github/workflows/nodejs_client_compatibility.yaml, .github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
[A warning is logged during the build](https://github.com/hazelcast/client-compatibility-suites/actions/runs/16020766406):
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Updated to resolve.
[Example execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/16021764635).
Closes: https://github.com/hazelcast/client-compatibility-suites/pull/163
=> Avoid deprecated `set-output` command

.github/workflows/go_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
[The tests fail](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15851234939) because older versions do not include https://github.com/hazelcast/hazelcast-go-client/pull/966.
Addressed by using the `rc.sh` from `master` - we already do something similar for C#.
[Example execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15897506864).
=> Fix older Go compatibility tests

.github/workflows/python_client_compatibility.yaml, .github/workflows/server_compatibility.yaml
The [tests are failing](https://github.com/hazelcast/client-compatibility-suites/actions/runs/15993342471) due to a known issue in [older versions](https://github.com/hazelcast/hazelcast-python-client/issues/666).
We should ignore those tests in the older versions as we know they won't pass and don't indicate any _new_ issues.
Changes:
- ignore `predicate_test` for <`5.5`
- merge `Run non-enterprise tests` & `Run all tests` into a single step
[Slack discussion](https://hazelcast.slack.com/archives/C092T6Q0MA8/p1751282784324389).
[Example execution](https://github.com/hazelcast/client-compatibility-suites/actions/runs/16003219803).
=> Fix Python compatibility tests due to paging predicate error
